interface ProductSeed {
  categorySlug: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  isFeatured: boolean;
  sortOrder: number;
  calories?: number;
  sugar?: number;
  fat?: number;
  protein?: number;
  caffeine?: number;
  ingredients?: string[];
  imageUrl?: string;
  variants: { name: string; sizeMl: number | null; priceModifier: number; isDefault: boolean; sortOrder: number }[];
}

export const productSeeds: ProductSeed[] = [
  // ── Beverages ─────────────────────────────────────
  {
    categorySlug: 'beverages',
    name: 'Caffè Latte',
    slug: 'caffe-latte',
    description: 'Our signature espresso meets steamed milk for a smooth, classic latte. Rich and comforting in every sip.',
    price: 45000,
    isFeatured: true,
    sortOrder: 1,
    calories: 180,
    sugar: 14,
    fat: 7,
    protein: 10,
    caffeine: 150,
    ingredients: ['Espresso', 'Steamed Milk', 'Foam'],
    imageUrl: 'https://picsum.photos/seed/caffe-latte/300/300',
    variants: [
      { name: 'Tall', sizeMl: 355, priceModifier: 0, isDefault: true, sortOrder: 1 },
      { name: 'Grande', sizeMl: 473, priceModifier: 5000, isDefault: false, sortOrder: 2 },
      { name: 'Venti', sizeMl: 591, priceModifier: 10000, isDefault: false, sortOrder: 3 },
    ],
  },
  {
    categorySlug: 'beverages',
    name: 'Latte Macchiato',
    slug: 'latte-macchiato',
    description: 'Layered espresso poured through steamed milk, marked with a dollop of foam. A beautifully structured latte.',
    price: 49000,
    isFeatured: false,
    sortOrder: 2,
    calories: 170,
    sugar: 12,
    fat: 6,
    protein: 9,
    caffeine: 150,
    ingredients: ['Espresso', 'Steamed Milk', 'Foam'],
    imageUrl: 'https://picsum.photos/seed/latte-macchiato/300/300',
    variants: [
      { name: 'Tall', sizeMl: 355, priceModifier: 0, isDefault: true, sortOrder: 1 },
      { name: 'Grande', sizeMl: 473, priceModifier: 5000, isDefault: false, sortOrder: 2 },
      { name: 'Venti', sizeMl: 591, priceModifier: 10000, isDefault: false, sortOrder: 3 },
    ],
  },
  {
    categorySlug: 'beverages',
    name: 'Caffè Mocha',
    slug: 'caffe-mocha',
    description: 'Espresso meets rich chocolate sauce and steamed milk, topped with whipped cream. Indulgent and satisfying.',
    price: 55000,
    isFeatured: true,
    sortOrder: 3,
    calories: 290,
    sugar: 32,
    fat: 12,
    protein: 11,
    caffeine: 150,
    ingredients: ['Espresso', 'Chocolate Sauce', 'Steamed Milk', 'Whipped Cream'],
    imageUrl: 'https://picsum.photos/seed/caffe-mocha/300/300',
    variants: [
      { name: 'Tall', sizeMl: 355, priceModifier: 0, isDefault: true, sortOrder: 1 },
      { name: 'Grande', sizeMl: 473, priceModifier: 5000, isDefault: false, sortOrder: 2 },
      { name: 'Venti', sizeMl: 591, priceModifier: 10000, isDefault: false, sortOrder: 3 },
    ],
  },
  {
    categorySlug: 'beverages',
    name: 'Americano',
    slug: 'americano',
    description: 'Espresso shots topped with hot water for a bold, clean coffee experience. Light body, deep flavor.',
    price: 39000,
    isFeatured: false,
    sortOrder: 4,
    calories: 10,
    sugar: 0,
    fat: 0,
    protein: 1,
    caffeine: 150,
    ingredients: ['Espresso', 'Hot Water'],
    imageUrl: 'https://picsum.photos/seed/americano/300/300',
    variants: [
      { name: 'Tall', sizeMl: 355, priceModifier: 0, isDefault: true, sortOrder: 1 },
      { name: 'Grande', sizeMl: 473, priceModifier: 5000, isDefault: false, sortOrder: 2 },
      { name: 'Venti', sizeMl: 591, priceModifier: 10000, isDefault: false, sortOrder: 3 },
    ],
  },
  {
    categorySlug: 'beverages',
    name: 'Caramel Macchiato',
    slug: 'caramel-macchiato',
    description: 'Freshly steamed milk with vanilla syrup, marked with espresso and finished with a crosshatch of caramel drizzle.',
    price: 55000,
    isFeatured: true,
    sortOrder: 5,
    calories: 200,
    sugar: 25,
    fat: 6,
    protein: 9,
    caffeine: 150,
    ingredients: ['Espresso', 'Steamed Milk', 'Vanilla Syrup', 'Caramel Drizzle'],
    imageUrl: 'https://picsum.photos/seed/caramel-macchiato/300/300',
    variants: [
      { name: 'Tall', sizeMl: 355, priceModifier: 0, isDefault: true, sortOrder: 1 },
      { name: 'Grande', sizeMl: 473, priceModifier: 5000, isDefault: false, sortOrder: 2 },
      { name: 'Venti', sizeMl: 591, priceModifier: 10000, isDefault: false, sortOrder: 3 },
    ],
  },
  {
    categorySlug: 'beverages',
    name: 'Iced Matcha Latte',
    slug: 'iced-matcha-latte',
    description: 'Premium matcha green tea powder whisked with milk and served over ice. Earthy, sweet, and refreshing.',
    price: 52000,
    isFeatured: false,
    sortOrder: 6,
    calories: 160,
    sugar: 18,
    fat: 4,
    protein: 8,
    caffeine: 80,
    ingredients: ['Matcha Powder', 'Milk', 'Ice'],
    imageUrl: 'https://picsum.photos/seed/iced-matcha-latte/300/300',
    variants: [
      { name: 'Tall', sizeMl: 355, priceModifier: 0, isDefault: true, sortOrder: 1 },
      { name: 'Grande', sizeMl: 473, priceModifier: 5000, isDefault: false, sortOrder: 2 },
      { name: 'Venti', sizeMl: 591, priceModifier: 10000, isDefault: false, sortOrder: 3 },
    ],
  },
  {
    categorySlug: 'beverages',
    name: 'Cold Brew Coffee',
    slug: 'cold-brew-coffee',
    description: 'Slow-steeped for 20 hours for a naturally sweet, smooth, full-bodied iced coffee experience.',
    price: 45000,
    isFeatured: true,
    sortOrder: 7,
    calories: 5,
    sugar: 0,
    fat: 0,
    protein: 1,
    caffeine: 200,
    ingredients: ['Cold Brew Coffee'],
    imageUrl: 'https://picsum.photos/seed/cold-brew-coffee/300/300',
    variants: [
      { name: 'Tall', sizeMl: 355, priceModifier: 0, isDefault: true, sortOrder: 1 },
      { name: 'Grande', sizeMl: 473, priceModifier: 5000, isDefault: false, sortOrder: 2 },
      { name: 'Venti', sizeMl: 591, priceModifier: 10000, isDefault: false, sortOrder: 3 },
    ],
  },
  {
    categorySlug: 'beverages',
    name: 'Mango Passion Fruit Refresher',
    slug: 'mango-passion-refresher',
    description: 'Tropical mango and passion fruit flavors shaken with ice for a vibrant, caffeine-free refresher.',
    price: 49000,
    isFeatured: false,
    sortOrder: 8,
    calories: 120,
    sugar: 26,
    fat: 0,
    protein: 0,
    caffeine: 0,
    ingredients: ['Mango Juice', 'Passion Fruit', 'Ice'],
    imageUrl: 'https://picsum.photos/seed/mango-passion-refresher/300/300',
    variants: [
      { name: 'Tall', sizeMl: 355, priceModifier: 0, isDefault: true, sortOrder: 1 },
      { name: 'Grande', sizeMl: 473, priceModifier: 5000, isDefault: false, sortOrder: 2 },
      { name: 'Venti', sizeMl: 591, priceModifier: 10000, isDefault: false, sortOrder: 3 },
    ],
  },
  // ── Food ──────────────────────────────────────────
  {
    categorySlug: 'food',
    name: 'Chicken & Avocado Sandwich',
    slug: 'chicken-avocado-sandwich',
    description: 'Grilled chicken breast with fresh avocado, lettuce, and tomato on artisan sourdough bread.',
    price: 55000,
    isFeatured: true,
    sortOrder: 1,
    calories: 420,
    sugar: 4,
    fat: 18,
    protein: 32,
    caffeine: 0,
    ingredients: ['Sourdough Bread', 'Grilled Chicken', 'Avocado', 'Lettuce', 'Tomato'],
    imageUrl: 'https://picsum.photos/seed/chicken-avocado-sandwich/300/300',
    variants: [],
  },
  {
    categorySlug: 'food',
    name: 'Ham & Cheese Croissant',
    slug: 'ham-cheese-croissant',
    description: 'Flaky butter croissant filled with smoked ham and melted Gruyère cheese. Warm and satisfying.',
    price: 45000,
    isFeatured: false,
    sortOrder: 2,
    calories: 380,
    sugar: 5,
    fat: 22,
    protein: 18,
    caffeine: 0,
    ingredients: ['Croissant', 'Smoked Ham', 'Gruyère Cheese'],
    imageUrl: 'https://picsum.photos/seed/ham-cheese-croissant/300/300',
    variants: [],
  },
  {
    categorySlug: 'food',
    name: 'Blueberry Muffin',
    slug: 'blueberry-muffin',
    description: 'Fresh-baked muffin loaded with wild blueberries and topped with a buttery streusel crumb.',
    price: 35000,
    isFeatured: false,
    sortOrder: 3,
    calories: 320,
    sugar: 28,
    fat: 14,
    protein: 5,
    caffeine: 0,
    ingredients: ['Flour', 'Blueberries', 'Sugar', 'Butter', 'Eggs'],
    imageUrl: 'https://picsum.photos/seed/blueberry-muffin/300/300',
    variants: [],
  },
  {
    categorySlug: 'food',
    name: 'Chocolate Chip Cookie',
    slug: 'chocolate-chip-cookie',
    description: 'Soft-baked classic cookie packed with semi-sweet chocolate chips. The perfect sweet treat.',
    price: 25000,
    isFeatured: false,
    sortOrder: 4,
    calories: 250,
    sugar: 20,
    fat: 12,
    protein: 3,
    caffeine: 0,
    ingredients: ['Flour', 'Chocolate Chips', 'Butter', 'Sugar', 'Eggs'],
    imageUrl: 'https://picsum.photos/seed/chocolate-chip-cookie/300/300',
    variants: [],
  },
  {
    categorySlug: 'food',
    name: 'Avocado Toast',
    slug: 'avocado-toast',
    description: 'Smashed avocado on toasted artisan bread with cherry tomatoes, red pepper flakes, and a squeeze of lime.',
    price: 42000,
    isFeatured: true,
    sortOrder: 5,
    calories: 280,
    sugar: 3,
    fat: 16,
    protein: 8,
    caffeine: 0,
    ingredients: ['Artisan Bread', 'Avocado', 'Cherry Tomatoes', 'Red Pepper Flakes', 'Lime'],
    imageUrl: 'https://picsum.photos/seed/avocado-toast/300/300',
    variants: [],
  },
  // ── Merchandise ───────────────────────────────────
  {
    categorySlug: 'merchandise',
    name: 'CFPV Ceramic Mug',
    slug: 'cfpv-ceramic-mug',
    description: 'Classic 12oz ceramic mug with the CFPV logo. Dishwasher and microwave safe.',
    price: 120000,
    isFeatured: false,
    sortOrder: 1,
    ingredients: ['Ceramic'],
    imageUrl: 'https://picsum.photos/seed/cfpv-ceramic-mug/300/300',
    variants: [],
  },
  {
    categorySlug: 'merchandise',
    name: 'CFPV Stainless Tumbler',
    slug: 'cfpv-stainless-tumbler',
    description: 'Double-wall insulated 16oz tumbler. Keeps drinks hot for 6 hours or cold for 12 hours.',
    price: 220000,
    isFeatured: false,
    sortOrder: 2,
    ingredients: ['Stainless Steel'],
    imageUrl: 'https://picsum.photos/seed/cfpv-stainless-tumbler/300/300',
    variants: [
      { name: 'Rose Gold', sizeMl: 473, priceModifier: 0, isDefault: true, sortOrder: 1 },
      { name: 'Matte Black', sizeMl: 473, priceModifier: 0, isDefault: false, sortOrder: 2 },
      { name: 'White', sizeMl: 473, priceModifier: 0, isDefault: false, sortOrder: 3 },
    ],
  },
  {
    categorySlug: 'merchandise',
    name: 'CFPV Tote Bag',
    slug: 'cfpv-tote-bag',
    description: 'Reusable canvas tote bag with the CFPV logo. Perfect for carrying your daily essentials.',
    price: 85000,
    isFeatured: false,
    sortOrder: 3,
    ingredients: ['Canvas'],
    imageUrl: 'https://picsum.photos/seed/cfpv-tote-bag/300/300',
    variants: [],
  },
  // ── At Home ────────────────────────────────────────
  {
    categorySlug: 'at-home',
    name: 'CFPV House Blend Beans',
    slug: 'cfpv-house-blend-beans',
    description: 'Our signature medium-roast blend with notes of chocolate and nuts. 250g bag of whole beans.',
    price: 95000,
    isFeatured: false,
    sortOrder: 1,
    caffeine: 180,
    ingredients: ['Arabica Coffee Beans'],
    imageUrl: 'https://picsum.photos/seed/cfpv-house-blend-beans/300/300',
    variants: [
      { name: 'Whole Bean', sizeMl: null, priceModifier: 0, isDefault: true, sortOrder: 1 },
      { name: 'Ground', sizeMl: null, priceModifier: 0, isDefault: false, sortOrder: 2 },
    ],
  },
  {
    categorySlug: 'at-home',
    name: 'Matcha Powder',
    slug: 'matcha-powder',
    description: 'Premium Japanese ceremonial-grade matcha green tea powder. 100g tin.',
    price: 150000,
    isFeatured: false,
    sortOrder: 2,
    caffeine: 60,
    ingredients: ['Matcha Green Tea Powder'],
    imageUrl: 'https://picsum.photos/seed/matcha-powder/300/300',
    variants: [],
  },
  {
    categorySlug: 'at-home',
    name: 'Pour-Over Kit',
    slug: 'pour-over-kit',
    description: 'Complete pour-over coffee set including ceramic dripper, paper filters, and a glass carafe.',
    price: 180000,
    isFeatured: false,
    sortOrder: 3,
    ingredients: ['Ceramic', 'Glass', 'Paper Filters'],
    imageUrl: 'https://picsum.photos/seed/pour-over-kit/300/300',
    variants: [],
  },
];
